Repository raphaelmue/dashup, pull requests merged in 2019-04, with the labels that each got.

#46 Load panel size
  de.dashup.model/src/main/java/de/dashup/model/builder/PanelLoader.java
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
  de.dashup.shared/src/main/java/de/dashup/shared/Panel.java
Labels: bug, enhancement

#55 Cucumber: implemented tests for change layout feature file
  de.dashup.application/src/main/webapp/views/includes/header.jsp
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.application/src/test/java/de.dashup.test/steps/ChangeLayoutStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/steps/GeneralStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/utils/DriverUtil.java
  de.dashup.application/src/test/resources/de.dashup.test/change_layout.feature
  docs/specifications/ucs/layout/change_layout/narratives/change_layout.feature
Labels: enhancement

#51 Prototyping for components
  de.dashup.application/src/main/webapp/components/dashupButton.js
  de.dashup.application/src/main/webapp/components/dashupComponent.js
  de.dashup.application/src/main/webapp/components/dashupGridLayout.js
  de.dashup.application/src/main/webapp/components/dashupInput.js
  de.dashup.application/src/main/webapp/components/dashupLabel.js
  de.dashup.application/src/main/webapp/components/dashupLayout.js
  de.dashup.application/src/main/webapp/components/dashupTextField.js
  de.dashup.application/src/main/webapp/html/dashupDisplay.html
  de.dashup.application/src/main/webapp/html/dashupGridLayout.html
  de.dashup.application/src/main/webapp/html/dashupInput.html
  de.dashup.application/src/main/webapp/html/dashupWeather.html
  de.dashup.application/src/main/webapp/views/includes/components/dashupButton.jsp
  de.dashup.application/src/main/webapp/views/includes/components/dashupGridLayout.jsp
  de.dashup.application/src/main/webapp/views/includes/components/dashupLabel.jsp
  de.dashup.application/src/main/webapp/views/includes/components/dashupTextField.jsp
  de.dashup.application/src/main/webapp/views/includes/webComponents.jsp
  de.dashup.model/src/main/java/de/dashup/model/builder/PanelLoader.java
  de.dashup.model/src/main/resources/de/dashup/model/builder/panels/1-large.html
  de.dashup.model/src/main/resources/de/dashup/model/builder/panels/1-medium.html
  de.dashup.model/src/main/resources/de/dashup/model/builder/panels/1-small.html
  docs/project management/Risk management.xlsx
  docs/project management/risk management.png
Labels: enhancement

#59 Jenkins database
  de.dashup.model/src/main/java/de/dashup/model/db/Database.java
Labels: Code improvement

#66 Fix codacy issues
  README.md
  de.dashup.application/src/main/java/de/dashup/application/DashupApplication.java
  de.dashup.application/src/main/java/de/dashup/application/controllers/EntryController.java
  de.dashup.application/src/main/java/de/dashup/application/controllers/LayoutModeController.java
  de.dashup.application/src/main/java/de/dashup/application/local/LocalStorage.java
  de.dashup.application/src/main/webapp/views/index.jsp
  de.dashup.application/src/main/webapp/views/login.jsp
  de.dashup.application/src/main/webapp/views/marketplace.jsp
  de.dashup.application/src/main/webapp/views/register.jsp
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.application/src/test/java/de.dashup.test/utils/DriverUtil.java
  de.dashup.shared/src/main/java/de/dashup/shared/DashupSectionStructure.java
  de.dashup.shared/src/main/java/de/dashup/shared/Panel.java
Labels: Code improvement

#70 Issue62
  de.dashup.application/pom.xml
  de.dashup.application/src/test/java/de.dashup.test/steps/ChangeLayoutStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/steps/GeneralStepDefinitions.java
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/utils/CucumberHooks.java
  de.dashup.application/src/test/java/de.dashup.test/utils/DriverUtil.java
  de.dashup.application/src/test/resources/de.dashup.test/login_register.feature
  de.dashup.model/src/test/java/de/dashup/test/ServiceLoginRegisterTest.java
  de.dashup.model/src/test/java/de/dashup/test/UnitTestUtil.java
  docs/specifications/ucs/user_management/login_register/narratives/login_register.feature
Labels: enhancement

#75 Automated deployment
  .idea/runConfigurations/RundashupTest.xml
  .idea/runConfigurations/dashup_Application__local_.xml
  Jenkinsfile
  de.dashup.application/src/test/java/de.dashup.test/RunDashupTest.java
  service/restart-application.sh
Labels: Code improvement, enhancement

#72 Settings enhancements according to specifications
  .idea/runConfigurations/RundashupTest.xml
  de.dashup.application/src/main/java/de/dashup/application/controllers/SettingsController.java
  de.dashup.application/src/main/java/de/dashup/application/controllers/util/ControllerHelper.java
  de.dashup.application/src/main/java/de/dashup/application/local/format/I18N.java
  de.dashup.application/src/main/resources/i18n.properties
  de.dashup.application/src/main/resources/i18n_de.properties
  de.dashup.application/src/main/resources/i18n_en.properties
  de.dashup.application/src/main/webapp/libraries/index.js
  de.dashup.application/src/main/webapp/styles/theme.style.css
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.application/src/test/java/de.dashup.test/steps/ChangeLayoutStepDefinitions.java
  de.dashup.application/src/test/java/de.dashup.test/steps/ChangeProfileStepDefinitions.java
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepDefinitions.java
  de.dashup.application/src/test/java/de.dashup.test/steps/SettingsStepDefinitions.java
  de.dashup.application/src/test/resources/de.dashup.test/change_profile.feature
  de.dashup.model/src/main/java/de/dashup/model/db/Converter.java
  de.dashup.model/src/main/java/de/dashup/model/exceptions/EmailAlreadyInUseException.java
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
  de.dashup.model/src/main/java/de/dashup/model/service/Validator.java
  de.dashup.model/src/test/java/de/dashup/test/ServiceSettingsTest.java
  de.dashup.shared/src/main/java/de/dashup/shared/DatabaseUser.java
  de.dashup.shared/src/main/java/de/dashup/shared/User.java
Labels: enhancement
