Repository raphaelmue/dashup, pull requests merged in 2019-05, with the labels that each got.

#98 Test hotfix concerning database changes
  de.dashup.application/src/main/webapp/views/layoutMode.jsp
  de.dashup.application/src/test/java/de.dashup.test/utils/CucumberHooks.java
  de.dashup.model/src/test/java/de/dashup/test/DatabaseUnitTest.java
  de.dashup.model/src/test/java/de/dashup/test/LayoutModeTest.java
  de.dashup.model/src/test/java/de/dashup/test/UnitTestUtil.java
Labels: bug

#94 Implement smoke tests
  Jenkinsfile
  de.dashup.application/pom.xml
  de.dashup.application/src/test/java/de.dashup.test/RunDashupTest.java
  de.dashup.application/src/test/java/de.dashup.test/utils/CucumberHooks.java
  de.dashup.application/src/test/java/de.dashup.test/utils/DriverUtil.java
  de.dashup.application/src/test/resources/de.dashup.test/change_layout.feature
  de.dashup.application/src/test/resources/de.dashup.test/change_profile.feature
  de.dashup.application/src/test/resources/de.dashup.test/login_register.feature
  de.dashup.model/pom.xml
  de.dashup.model/src/test/java/de/dashup/test/DatabaseUnitTest.java
  de.dashup.model/src/test/java/de/dashup/test/ServiceLoginRegisterTest.java
  de.dashup.model/src/test/java/de/dashup/test/ServiceSettingsTest.java
  de.dashup.util/src/main/java/de/dashup/util/string/Hash.java
  de.dashup.util/src/main/java/de/dashup/util/string/RandomString.java
  de.dashup.util/src/test/java/de/dashup/util/string/HashTest.java
  de.dashup.util/src/test/java/de/dashup/util/string/RandomStringTest.java
  docs/architectures/testing/test_plan.md
  pom.xml
Labels: tests

#87 Export code coverage to codacy
  .gitignore
  Jenkinsfile
  README.md
  pom.xml
  service/publish-test-report.sh
Labels: Code improvement

#79 First draft of workbench
  de.dashup.application/src/main/java/de/dashup/application/controllers/MarketplaceController.java
  de.dashup.application/src/main/java/de/dashup/application/controllers/WorkbenchController.java
  de.dashup.application/src/main/resources/i18n.properties
  de.dashup.application/src/main/resources/i18n_de.properties
  de.dashup.application/src/main/resources/i18n_en.properties
  de.dashup.application/src/main/webapp/libraries/index.js
  de.dashup.application/src/main/webapp/styles/main.style.css
  de.dashup.application/src/main/webapp/styles/mainDashboard.css
  de.dashup.application/src/main/webapp/styles/theme.style.css
  de.dashup.application/src/main/webapp/views/index.jsp
  de.dashup.application/src/main/webapp/views/workbench.jsp
  de.dashup.model/pom.xml
  de.dashup.model/src/main/java/de/dashup/model/builder/DashupBuilder.java
  de.dashup.model/src/main/java/de/dashup/model/db/Database.java
  de.dashup.model/src/main/java/de/dashup/model/exceptions/InvalidCodeException.java
  de.dashup.model/src/main/java/de/dashup/model/exceptions/MissingInformationException.java
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
  de.dashup.model/src/main/java/de/dashup/model/service/Validator.java
  de.dashup.model/src/test/java/de/dashup/test/service/ValidatorTest.java
  de.dashup.shared/src/main/java/de/dashup/shared/DatabaseTag.java
  de.dashup.shared/src/main/java/de/dashup/shared/DatabaseWidget.java
  de.dashup.shared/src/main/java/de/dashup/shared/Draft.java
  de.dashup.shared/src/main/java/de/dashup/shared/Tag.java
  de.dashup.shared/src/main/java/de/dashup/shared/User.java
  de.dashup.shared/src/main/java/de/dashup/shared/Widget.java
Labels: enhancement

#105 Properties issue
  de.dashup.application/src/main/java/de/dashup/application/controllers/LayoutModeController.java
  de.dashup.application/src/main/java/de/dashup/application/controllers/WorkbenchController.java
  de.dashup.application/src/main/resources/i18n.properties
  de.dashup.application/src/main/resources/i18n_de.properties
  de.dashup.application/src/main/resources/i18n_en.properties
  de.dashup.application/src/main/webapp/views/layoutMode.jsp
  de.dashup.application/src/main/webapp/views/workbench.jsp
  de.dashup.model/src/main/java/de/dashup/model/db/Database.java
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
  de.dashup.shared/pom.xml
  de.dashup.shared/src/main/java/de/dashup/shared/DatabaseProperty.java
  de.dashup.shared/src/main/java/de/dashup/shared/Property.java
  de.dashup.shared/src/main/java/de/dashup/shared/Widget.java
Labels: enhancement
