Repository raphaelmue/dashup, pull requests merged in 2019-03, with the labels that each got.

#20 Fixed remember me issue
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
Labels: bug

#33 Fixed issue #16
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
Labels: bug

#34 Themes
  de.dashup.application/src/main/java/de/dashup/application/controllers/EntryController.java
  de.dashup.application/src/main/webapp/styles/theme.style.css
  de.dashup.application/src/main/webapp/styles/themes/theme.black-night.style.css
  de.dashup.application/src/main/webapp/styles/themes/theme.blue-sky.style.css
  de.dashup.application/src/main/webapp/styles/themes/theme.green-nature.style.css
  de.dashup.application/src/main/webapp/styles/themes/theme.red-love.style.css
  de.dashup.application/src/main/webapp/styles/themes/theme.white-diamond.style.css
  de.dashup.application/src/main/webapp/views/includes/head.jsp
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.shared/src/main/java/de/dashup/shared/Settings.java
Labels: enhancement

#47 Token error
  de.dashup.application/src/main/java/de/dashup/application/local/LocalStorage.java
Labels: bug

#49 Dashup icon clickable
  de.dashup.application/src/main/webapp/views/includes/header.jsp
  de.dashup.application/src/main/webapp/views/login.jsp
  de.dashup.application/src/main/webapp/views/register.jsp
Labels: enhancement

#48 Validate password length
  de.dashup.application/src/main/resources/i18n.properties
  de.dashup.application/src/main/resources/i18n_de.properties
  de.dashup.application/src/main/resources/i18n_en.properties
  de.dashup.application/src/main/webapp/views/register.jsp
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepdefs.java
  de.dashup.application/src/test/resources/de.dashup.test/login_register.feature
Labels: enhancement

#52 Fixing codacy issues
  de.dashup.application/src/main/java/de/dashup/application/controllers/LayoutModeController.java
  de.dashup.application/src/main/webapp/libraries/classes/PostRequest.js
  de.dashup.application/src/main/webapp/libraries/dragdrop.js
  de.dashup.application/src/main/webapp/libraries/index.js
  de.dashup.application/src/main/webapp/styles/layoutmode.css
  de.dashup.application/src/main/webapp/views/includes/head.jsp
  de.dashup.application/src/main/webapp/views/includes/header.jsp
  de.dashup.application/src/main/webapp/views/includes/mainLayout.jsp
  de.dashup.application/src/main/webapp/views/includes/webComponents.jsp
  de.dashup.application/src/main/webapp/views/index.jsp
  de.dashup.application/src/main/webapp/views/layoutMode.jsp
  de.dashup.application/src/main/webapp/views/register.jsp
  de.dashup.application/src/main/webapp/views/settings.jsp
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/utils/DriverUtil.java
  de.dashup.model/src/main/java/de/dashup/model/builder/PanelLoader.java
  de.dashup.model/src/main/java/de/dashup/model/db/Database.java
  de.dashup.model/src/main/java/de/dashup/model/service/DashupService.java
  de.dashup.shared/src/main/java/de/dashup/shared/DashupPanelInformation.java
  de.dashup.shared/src/main/java/de/dashup/shared/DashupPanelStructure.java
  de.dashup.shared/src/main/java/de/dashup/shared/DashupSectionStructure.java
  de.dashup.shared/src/main/java/de/dashup/shared/Section.java
Labels: Code improvement

#57 Issue56
  de.dashup.application/src/test/java/de.dashup.test/steps/GeneralStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/steps/LoginRegisterStepdefs.java
  de.dashup.application/src/test/java/de.dashup.test/utils/CucumberHooks.java
  de.dashup.application/src/test/resources/de.dashup.test/login_register.feature
Labels: enhancement
